.TH WMFTOPNG 1 "January 4, 2001"
.SH NAME
wmftopng \- convert WMF files to PNG format
.SH SYNOPSIS
.B wmftopng
.I file.wmf
.I output.png
[
.I ttffontdir
]
.SH DESCRIPTION
.B wmftopng
converts Windows Metafiles (WMF) to PNG format.  It uses the libwmf library.
.PP
.I ttffontdir
specifies an alternative directory containing TrueType fonts.
.SH AUTHORS
Caolan McNamara <Caolan.McNamara@ul.ie>, Martin Vermeer
<martin.vermeer@hut.fi>.
.PP
This manual page was written by Matej Vela <vela@debian.org>.
