.TH WMFTOFIG 1 "January 4, 2001"
.SH NAME
wmftofig \- convert WMF files to XFig format
.SH SYNOPSIS
.B wmftofig
.I file.wmf
.I output.fig
.SH DESCRIPTION
.B wmftofig
converts Windows Metafiles (WMF) to XFig format.  It uses the libwmf library.
.SH AUTHORS
David Airlie <David.Airlie@ul.ie>, Caolan McNamara <Caolan.McNamara@ul.ie>,
Martin Vermeer <martin.vermeer@hut.fi>, Frederic Vivien.
.PP
This manual page was written by Matej Vela <vela@debian.org>.
