.TH WMFTOEPS 1 "January 4, 2001"
.SH NAME
wmftoeps \- convert WMF files to Encapsulated PostScript
.SH SYNOPSIS
.B wmftoeps
.I file.wmf
.I output.eps
.SH DESCRIPTION
.B wmftoeps
converts Windows Metafiles (WMF) to Encapsulated PostScript.  It uses the
libwmf library.
.SH CAVEATS
.B wmftoeps
is incomplete and still in development.
.SH AUTHORS
Martin Vermeer <martin.vermeer@hut.fi>.
.PP
This manual page was written by Matej Vela <vela@debian.org>.
