.TH XWMF 1 "January 4, 2001"
.SH NAME
xwmf \- display a WMF file in an X window
.SH SYNOPSIS
.B xwmf
.I file.wmf
.SH DESCRIPTION
.B xwmf
displays a Windows Metafile (WMF) in an X window.  It uses the libwmf library.
.PP
Zooming in and out is possible by pressing `+' and `-', respectively.
.SH AUTHORS
Caolan McNamara <Caolan.McNamara@ul.ie>, Raj Manandhar <raj@colsa.com>.
.PP
This manual page was written by Matej Vela <vela@debian.org>.
